int a,b,c,pil;
char jawab;
do {cout<<"Masukkan pilihan (1-5):  "; cin>>pil;
	switch(pil){
		case 1: cout<<"Masukkan angka pertama: "; cin>>a;
				cout<<"Masukkan angka kedua: "; cin>>b;
				c = a + b;
				cout<<"Hasil Penjumlahan: "<<c<<endl;
		break;
		case 2: cout<<"Masukkan angka pertama: "; cin>>a;
				cout<<"Masukkan angka kedua: "; cin>>b;
				c = a - b;
				cout<<"Hasil Pengurangan: "<<c<<endl;
		break;
		case 3: cout<<"Masukkan angka pertama: "; cin>>a;
				cout<<"Masukkan angka kedua: "; cin>>b;
				c = a * b;
				cout<<"Hasil Perkalian: "<<c<<endl;
		break;
		case 4: cout<<"Masukkan angka pertama: "; cin>>a;
				cout<<"Masukkan angka kedua: "; cin>>b;
				c = a / b;
				cout<<"Hasil Pembagian: "<<c<<endl; 
		case 5: cout<<"Masukkan angka pertama: "; cin>>a;
				cout<<"Masukkan angka kedua: "; cin>>b;
				c = a % b;
				cout<<"Hasil Modulos: "<<c<<endl;
				break;
		default: cout<<"Program Error "<<endl;
